package data;

import java.math.BigDecimal;
import java.util.ArrayList;

import org.joda.time.DateTime;

public class Precio {
	
	private DateTime fechaInicio;
	private DateTime fechaFin;
	private DateTime fechaCreacion;
	
	private BigDecimal monto;
	
	public Precio(DateTime inicio, DateTime fin, BigDecimal monto) {
		this.fechaInicio = new DateTime(inicio);
		this.fechaFin = new DateTime(fin);
		
		this.fechaCreacion = new DateTime();//Today
		
		this.monto = monto;
	}

	public DateTime getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(DateTime fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public DateTime getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(DateTime fechaFin) {
		this.fechaFin = fechaFin;
	}

	public DateTime getFechaCreacion() {
		return fechaCreacion;
	}

	public BigDecimal getMonto() {
		return monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fechaCreacion == null) ? 0 : fechaCreacion.hashCode());
		result = prime * result + ((fechaFin == null) ? 0 : fechaFin.hashCode());
		result = prime * result + ((fechaInicio == null) ? 0 : fechaInicio.hashCode());
		result = prime * result + ((monto == null) ? 0 : monto.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		//AutoGenerated :D
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Precio other = (Precio) obj;
		if (fechaCreacion == null) {
			if (other.fechaCreacion != null)
				return false;
		} else if (!fechaCreacion.equals(other.fechaCreacion))
			return false;
		if (fechaFin == null) {
			if (other.fechaFin != null)
				return false;
		} else if (!fechaFin.equals(other.fechaFin))
			return false;
		if (fechaInicio == null) {
			if (other.fechaInicio != null)
				return false;
		} else if (!fechaInicio.equals(other.fechaInicio))
			return false;
		if (monto == null) {
			if (other.monto != null)
				return false;
		} else if (!monto.equals(other.monto))
			return false;
		return true;
	}
	

}
